CREATE TABLE machine (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    name VARCHAR(255) NOT NULL,
    make VARCHAR(255),
    machine_type VARCHAR(255),
    status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Inactive',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
